ignoredBuiltDependencies:
  - "@modelcontextprotocol/ext-apps"
  - esbuild

overrides:
  hono@<4.12.2: ">=4.12.2"
  minimatch@<10.2.1: ">=10.2.1"

patchedDependencies:
  "@modelcontextprotocol/sdk": patches/@modelcontextprotocol__sdk.patch
