name: GitHub Pages

on:
  workflow_run:
    workflows:
      - Docs
    types:
      - completed

jobs:
  deploy_pages:
    permissions:
      pages: write
      id-token: write

    if: github.actor != 'nektos/act' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
