name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_pages:
    permissions:
      contents: read

    if: github.actor != 'nektos/act'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/docs.yaml
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs

  deploy_pages:
    permissions:
      pages: write
      id-token: write

    needs: build_pages

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
