name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_pages:
    uses: ./.github/workflows/docs.yaml

  deploy_pages:
    permissions:
      pages: write
      id-token: write

    needs: build_pages

    if: github.actor != 'nektos/act'

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/download-artifact@v5
        with:
          name: docs
          path: docs

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs

      - id: deployment
        uses: actions/deploy-pages@v4
