name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_pages:
    uses: ./.github/workflows/docs.yaml

  deploy_pages:
    permissions:
      pages: write
      id-token: write

    needs: build_pages

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: docs
