name: IPFS

on:
  workflow_run:
    workflows:
      - Docs
    types:
      - completed

jobs:
  ipfs:
    permissions:
      contents: read
      pull-requests: write
      statuses: write

    if: github.actor != 'nektos/act' && github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    environment:
      name: ipfs
      url: ${{ steps.url.outputs.url }}

    steps:
      - uses: actions/download-artifact@v5
        with:
          github-token: ${{ github.token }}
          name: docs
          path: docs
          run-id: ${{ github.event.workflow_run.id }}

      - id: deploy
        uses: ipfs/ipfs-deploy-action@v1
        with:
          github-token: ${{ github.token }}
          ipfs-add-options: --chunker=buzhash --cid-version=1 --hash=blake3 --pin=false
          kubo-api-auth: ${{ secrets.KUBO_API_AUTH }}
          kubo-api-url: ${{ secrets.KUBO_API_URL }}
          path-to-deploy: docs

      - if: github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main'
        run: ipfs --api "$KUBO_API_URL" --api-auth "$KUBO_API_AUTH" name publish --key=@natoboram/based.ts "/ipfs/$CID"
        env:
          CID: ${{ steps.deploy.outputs.cid }}
          KUBO_API_AUTH: ${{ secrets.KUBO_API_AUTH }}
          KUBO_API_URL: ${{ secrets.KUBO_API_URL }}

      - id: url
        if: steps.deploy.outputs.cid
        run: echo "url=https://$CID.ipfs.dweb.link" >> "$GITHUB_OUTPUT"
        env:
          CID: ${{ steps.deploy.outputs.cid }}
