name: Node.js Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      packages: write

    if: github.actor != 'nektos/act'

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 23
      - run: pnpm install
      - run: pnpm build

      - run: |
          pnpm config set @natoboram:registry 'https://npm.pkg.github.com'
          pnpm config set //npm.pkg.github.com/:_authToken '${NODE_AUTH_TOKEN}'
          pnpm publish --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          pnpm config set @natoboram:registry 'https://registry.npmjs.org'
          pnpm config set //registry.npmjs.org/:_authToken '${NODE_AUTH_TOKEN}'
          pnpm publish --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm pack --pack-gzip-level 9

      - run: gh release create "$VERSION" --generate-notes --title "$VERSION" --verify-tag natoboram-based.ts-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref_name }}
